notifications:
  recipients:
    - rcairo@ml.commit-email.info
sudo: true
addons:
  apt:
    update: true
rvm:
  - 2.1
  - 2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
before_install:
  - gem update bundler
  - gem install cairo
