notifications:
  webhooks:
    - https://webhook.commit-email.info/
sudo: true
addons:
  apt:
    update: true
rvm:
  - 2.1
  - 2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
before_install:
  - gem update bundler
  # Need to install cairo gem as a normal gem to find rb_cairo.h by
  # other gems cairo-gobject gem and so on.
  - gem build cairo.gemspec
  - gem install *.gem
install:
  - bundle install --jobs=3 --retry=3
