version: "{build}"
clone_depth: 10

notifications:
  - provider: Email
    to:
      - rcairo@ml.commit-email.info
    on_build_status_changed: true

environment:
  matrix:
    - ruby_version: "21"
      mingw_arch: "32"
    - ruby_version: "21-x64"
      mingw_arch: "64"
    - ruby_version: "22"
      mingw_arch: "32"
    - ruby_version: "22-x64"
      mingw_arch: "64"
    - ruby_version: "23"
      mingw_arch: "32"
    - ruby_version: "23-x64"
      mingw_arch: "64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\Ruby%ruby_version%\DevKit\bin;%PATH%
  - SET PATH=C:\Ruby%ruby_version%\DevKit\mingw\bin;%PATH%
  - dir C:\Ruby%ruby_version%
  - dir C:\Ruby%ruby_version%\DevKit\bin
  - dir C:\Ruby%ruby_version%\DevKit\mingw\bin
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-document
  - bundler --version
  - bundle install

build_script:
  - bundle exec ruby extconf.rb
  - bundle exec make

test_script:
  - SET PATH=C:\msys64\mingw%mingw_arch%\bin;%PATH%
  - bundle exec rake
